name: Resharper Code Analysis
 
on: 
    push:
        branches: [master]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: Run resharper inspection
        run: jb inspectcode EnvironmentMonitoringSystem.sln /output=insreport.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder EnvironmentMonitoringSystem.sln /output=dupreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1
